name: Test and Deploy

on:
  # Cloudflare only deploys the "main" branch to Production. All other branches
  # (like PRs) are deployed as previews.
  push:
    branches:
      - "main"
  pull_request:

  # Allow Manual Runs
  workflow_dispatch:

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Static Analysis
        uses: ./.github/actions/static-analysis

  publish:
    name: Publish to Cloudflare Pages
    # needs: static-analysis
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        shell: bash
        run: npm run build:production

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=${{ secrets.CLOUDFLARE_PAGES_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
