name: Update Schedule Data
on:
  schedule:
    - cron: "0 0 15 3 *" # March 15th at midnight UTC (just before the start of the season)
    - cron: "0 0 29 9 *" # September 29th at midnight UTC (just before the end of the season)
    - cron: "0 0 * 10 *" # Every day in October at midnight UTC (to update the schedule throughout the post-season)
  workflow_dispatch: ~

jobs:
  update-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Establish variables
        id: vars
        run: |
          echo "year=$(date +'%Y')" >> "$GITHUB_OUTPUT"
          echo "team=rockies" >> "$GITHUB_OUTPUT"

      - name: Update MLB team schedule
        run: make prepare-schedule team=${{ steps.vars.outputs.team }} year=${{ steps.vars.outputs.year }}

      - name: Commit new schedule data
        uses: EndBug/add-and-commit@v9
        with:
          add: 'src/game-data/schedule.json'
          default_author: github_actions
          message: "Updated Schedule [skip actions]" # https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
          push: '--force'
